# Generated by Django 3.1.4 on 2020-12-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='proccessor_freq',
            new_name='processor_freq',
        ),
    ]
